name: CI - Python (pip)

# Run on push to any branch and on PRs; also allow manual trigger
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch: {}

jobs:
  test:
    name: Test on ${{ matrix.python-version }} / ${{ runner.os }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.11]   # test on multiple Python versions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest -q

      - name: Upload test logs (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-logs
          path: ./pytest.log   # create a log in your tests step if desired
